// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"ipfsdisk/service/account/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/pb/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pb/register",
				Handler: registerHandler(serverCtx),
			},
		},
	)
}
