// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"ipfsdisk/service/user/rpc/internal/logic"
	"ipfsdisk/service/user/rpc/internal/svc"
	"ipfsdisk/service/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

//  用户登录
func (s *UserServer) UserLogin(ctx context.Context, in *user.LoginReq) (*user.UserLoginResponse, error) {
	l := logic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}

//  用户注册
func (s *UserServer) UserResister(ctx context.Context, in *user.ResisterReq) (*user.UserLoginResponse, error) {
	l := logic.NewUserResisterLogic(ctx, s.svcCtx)
	return l.UserResister(in)
}

//  修改密码
func (s *UserServer) UserChangePasswd(ctx context.Context, in *user.ChangePasswdReq) (*user.MsgResponse, error) {
	l := logic.NewUserChangePasswdLogic(ctx, s.svcCtx)
	return l.UserChangePasswd(in)
}
