// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"ipfsdisk/service/user/rpc/internal/logic"
	"ipfsdisk/service/user/rpc/internal/svc"
	"ipfsdisk/service/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) UserLogin(ctx context.Context, in *user.LoginReq) (*user.LoginResponse, error) {
	l := logic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}
