// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"ipfsdisk/service/account/rpc/internal/logic"
	"ipfsdisk/service/account/rpc/internal/svc"
	"ipfsdisk/service/account/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// UserLogin 用户登录
func (s *UserServer) UserLogin(ctx context.Context, in *pb.LoginReq) (*pb.LoginResponse, error) {
	l := logic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}

// UserResister 用户注册
func (s *UserServer) UserResister(ctx context.Context, in *pb.ResisterReq) (*pb.LoginResponse, error) {
	l := logic.NewUserResisterLogic(ctx, s.svcCtx)
	return l.UserResister(in)
}

// UserChangePasswd 修改密码
func (s *UserServer) UserChangePasswd(ctx context.Context, in *pb.ChangePasswdReq) (*pb.MsgResponse, error) {
	l := logic.NewUserChangePasswdLogic(ctx, s.svcCtx)
	return l.UserChangePasswd(in)
}
